### ISSUE TITLE
Include tests in PyPI tarball

### ISSUE THREAD

**Issue by jluttine** [delfick/nose-focus#4]
Could you include unit tests in the release tarball in PyPI? I think it's quite common practice.

Some references:

- https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute
- https://stackoverflow.com/a/20180000

I'm packaging nose-focus for a Linux distro so as part of the build process I'd like to run the unit tests.

**Comment by delfick** [comment]
Hi,

I'm not sure including tests in a package is common practise, or even a good thing.

Also, it should be up to me to make sure https://travis-ci.org/delfick/nose-focus is passing before I upload to pypi, rather than you're responsibility to check the package I uploaded passes it's tests.

**Comment by delfick** [comment]
Mind you, the release on https://github.com/delfick/nose-focus/releases contains the tests as well, so if you use that then you should be able to get to the tests anyway

**Comment by delfick** [comment]
Right, fair enough.

I suppose I could use a MANIFEST.in to include the tests package and then setup.py essentially ignores them when it installs the package. Is it more difficult to use the github releases then it is to get the source tarball from pypi? 

Interestingly I was reminded that I had made this in the first place (I don't really ever use it to be honest) and had a need for it today. But it didn't work because the wantMethod hook on the plugin doesn't get run if another plugin has it's own wantMethod hook and that returns a non-None value! Took me a while to work out why it wasn't working cause I also use https://noseofyeti.readthedocs.io/en/latest/ and it's wantMethod hook was running before nose focus' wantMethod hook.
